"""empty message

Revision ID: 161cf511c803
Revises: 7223e7dc5e30
Create Date: 2018-01-18 10:24:18.540242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161cf511c803'
down_revision = '7223e7dc5e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
